#!/usr/bin/env bash
set -euo pipefail

: "${TELEGRAM_PPC_CI_ROOT:?TELEGRAM_PPC_CI_ROOT is required}"
: "${TELEGRAM_PPC_FFMPEG_VERSION:=8.0}"

src_root="$TELEGRAM_PPC_CI_ROOT/src"
ffmpeg_archive="$src_root/ffmpeg-${TELEGRAM_PPC_FFMPEG_VERSION}.tar.xz"
ffmpeg_src="$src_root/ffmpeg-${TELEGRAM_PPC_FFMPEG_VERSION}"

mkdir -p "$src_root"

if [ ! -x "$ffmpeg_src/configure" ]; then
  if [ ! -f "$ffmpeg_archive" ]; then
    curl -fsSL "https://ffmpeg.org/releases/ffmpeg-${TELEGRAM_PPC_FFMPEG_VERSION}.tar.xz" -o "$ffmpeg_archive"
  fi
  tar -xf "$ffmpeg_archive" -C "$src_root"
fi

cat > "$TELEGRAM_PPC_CI_ROOT/ffmpeg-build-config.sh" <<EOF
#!/usr/bin/env bash
export TELEGRAM_PPC_BUILD_ROOT="$TELEGRAM_PPC_CI_ROOT/build"
export TELEGRAM_PPC_SDK_ROOT="$TELEGRAM_PPC_SDK_ROOT"
export TELEGRAM_PPC_LIPO="$TELEGRAM_PPC_LIPO"
export TELEGRAM_PPC_PPC_CC="$TELEGRAM_PPC_PPC_CC"
export TELEGRAM_PPC_I386_CC="$TELEGRAM_PPC_I386_CC"
export TELEGRAM_PPC_X86_64_CC="$TELEGRAM_PPC_X86_64_CC"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_ROOT="$TELEGRAM_PPC_CI_ROOT/deps/ppc/ffmpeg"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_ROOT="$TELEGRAM_PPC_CI_ROOT/deps/i386/ffmpeg"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_ROOT="$TELEGRAM_PPC_CI_ROOT/deps/x86_64/ffmpeg"
export TELEGRAM_PPC_FFMPEG_SOURCE="$ffmpeg_src"
export TELEGRAM_PPC_JOBS="${TELEGRAM_PPC_JOBS:-2}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
EOF

scripts/build-ffmpeg-static.sh --config "$TELEGRAM_PPC_CI_ROOT/ffmpeg-build-config.sh" --arch all

{
  echo "TELEGRAM_PPC_PPC_FFMPEG_ROOT=$TELEGRAM_PPC_CI_ROOT/deps/ppc/ffmpeg"
  echo "TELEGRAM_PPC_I386_FFMPEG_ROOT=$TELEGRAM_PPC_CI_ROOT/deps/i386/ffmpeg"
  echo "TELEGRAM_PPC_X86_64_FFMPEG_ROOT=$TELEGRAM_PPC_CI_ROOT/deps/x86_64/ffmpeg"
} >> "$GITHUB_ENV"
