#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local name=$1
  if [ -z "${!name:-}" ]; then
    echo "required environment variable is empty: $name" >&2
    exit 1
  fi
}

for name in \
  DARWIN_LEGACY_CROSS_BUILD_ROOT \
  DARWIN_LEGACY_CROSS_DIST_DIR \
  DARWIN_LEGACY_CROSS_DEPENDENCY_ROOTS \
  DARWIN_LEGACY_SDK_ROOT \
  DARWIN_INSTALL_NAME_TOOL \
  DARWIN_OTOOL \
  DARWIN_LIPO \
  DARWIN_CA_BUNDLE \
  DARWIN_PPC_CC \
  DARWIN_PPC_CXX \
  DARWIN_I386_CC \
  DARWIN_I386_CXX \
  DARWIN_X86_64_CC \
  DARWIN_X86_64_CXX \
  DARWIN_ARM64_CC \
  DARWIN_ARM64_CXX \
  DARWIN_PPC_CURL_ROOT \
  DARWIN_I386_CURL_ROOT \
  DARWIN_X86_64_CURL_ROOT \
  DARWIN_ARM64_CURL_ROOT \
  DARWIN_PPC_OPENSSL_ROOT \
  DARWIN_I386_OPENSSL_ROOT \
  DARWIN_X86_64_OPENSSL_ROOT \
  DARWIN_ARM64_OPENSSL_ROOT \
  DARWIN_PPC_ZLIB_ROOT \
  DARWIN_I386_ZLIB_ROOT \
  DARWIN_X86_64_ZLIB_ROOT \
  DARWIN_ARM64_ZLIB_ROOT \
  DARWIN_PPC_TDLIB_LIBRARY \
  DARWIN_I386_TDLIB_LIBRARY \
  DARWIN_X86_64_TDLIB_LIBRARY \
  DARWIN_ARM64_TDLIB_LIBRARY; do
  require_env "$name"
done

export TELEGRAM_PPC_BUILD_ROOT="${TELEGRAM_PPC_BUILD_ROOT:-$DARWIN_LEGACY_CROSS_BUILD_ROOT}"
export TELEGRAM_PPC_DIST_DIR="${TELEGRAM_PPC_DIST_DIR:-$DARWIN_LEGACY_CROSS_DIST_DIR}"
export TELEGRAM_PPC_DEPENDENCY_ROOTS="${TELEGRAM_PPC_DEPENDENCY_ROOTS:-$DARWIN_LEGACY_CROSS_DEPENDENCY_ROOTS}"
export TELEGRAM_PPC_SDK_ROOT="${TELEGRAM_PPC_SDK_ROOT:-$DARWIN_LEGACY_SDK_ROOT}"
export TELEGRAM_PPC_ARM64_SDK_ROOT="${TELEGRAM_PPC_ARM64_SDK_ROOT:-${DARWIN_ARM64_SDK_ROOT:-}}"
export TELEGRAM_PPC_INSTALL_NAME_TOOL="${TELEGRAM_PPC_INSTALL_NAME_TOOL:-$DARWIN_INSTALL_NAME_TOOL}"
export TELEGRAM_PPC_OTOOL="${TELEGRAM_PPC_OTOOL:-$DARWIN_OTOOL}"
export TELEGRAM_PPC_LIPO="${TELEGRAM_PPC_LIPO:-$DARWIN_LIPO}"
export TELEGRAM_PPC_CA_BUNDLE="${TELEGRAM_PPC_CA_BUNDLE:-$DARWIN_CA_BUNDLE}"

export TELEGRAM_PPC_PPC_CC="${TELEGRAM_PPC_PPC_CC:-$DARWIN_PPC_CC}"
export TELEGRAM_PPC_PPC_CXX="${TELEGRAM_PPC_PPC_CXX:-$DARWIN_PPC_CXX}"
export TELEGRAM_PPC_I386_CC="${TELEGRAM_PPC_I386_CC:-$DARWIN_I386_CC}"
export TELEGRAM_PPC_I386_CXX="${TELEGRAM_PPC_I386_CXX:-$DARWIN_I386_CXX}"
export TELEGRAM_PPC_X86_64_CC="${TELEGRAM_PPC_X86_64_CC:-$DARWIN_X86_64_CC}"
export TELEGRAM_PPC_X86_64_CXX="${TELEGRAM_PPC_X86_64_CXX:-$DARWIN_X86_64_CXX}"
export TELEGRAM_PPC_ARM64_CC="${TELEGRAM_PPC_ARM64_CC:-$DARWIN_ARM64_CC}"
export TELEGRAM_PPC_ARM64_CXX="${TELEGRAM_PPC_ARM64_CXX:-$DARWIN_ARM64_CXX}"

export TELEGRAM_PPC_PPC_FFMPEG_ROOT="${TELEGRAM_PPC_PPC_FFMPEG_ROOT:-${DARWIN_PPC_FFMPEG_ROOT:-}}"
export TELEGRAM_PPC_I386_FFMPEG_ROOT="${TELEGRAM_PPC_I386_FFMPEG_ROOT:-${DARWIN_I386_FFMPEG_ROOT:-}}"
export TELEGRAM_PPC_X86_64_FFMPEG_ROOT="${TELEGRAM_PPC_X86_64_FFMPEG_ROOT:-${DARWIN_X86_64_FFMPEG_ROOT:-}}"
export TELEGRAM_PPC_ARM64_FFMPEG_ROOT="${TELEGRAM_PPC_ARM64_FFMPEG_ROOT:-${DARWIN_ARM64_FFMPEG_ROOT:-}}"

export TELEGRAM_PPC_PPC_CURL_ROOT="${TELEGRAM_PPC_PPC_CURL_ROOT:-$DARWIN_PPC_CURL_ROOT}"
export TELEGRAM_PPC_I386_CURL_ROOT="${TELEGRAM_PPC_I386_CURL_ROOT:-$DARWIN_I386_CURL_ROOT}"
export TELEGRAM_PPC_X86_64_CURL_ROOT="${TELEGRAM_PPC_X86_64_CURL_ROOT:-$DARWIN_X86_64_CURL_ROOT}"
export TELEGRAM_PPC_ARM64_CURL_ROOT="${TELEGRAM_PPC_ARM64_CURL_ROOT:-$DARWIN_ARM64_CURL_ROOT}"
export TELEGRAM_PPC_PPC_OPENSSL_ROOT="${TELEGRAM_PPC_PPC_OPENSSL_ROOT:-$DARWIN_PPC_OPENSSL_ROOT}"
export TELEGRAM_PPC_I386_OPENSSL_ROOT="${TELEGRAM_PPC_I386_OPENSSL_ROOT:-$DARWIN_I386_OPENSSL_ROOT}"
export TELEGRAM_PPC_X86_64_OPENSSL_ROOT="${TELEGRAM_PPC_X86_64_OPENSSL_ROOT:-$DARWIN_X86_64_OPENSSL_ROOT}"
export TELEGRAM_PPC_ARM64_OPENSSL_ROOT="${TELEGRAM_PPC_ARM64_OPENSSL_ROOT:-$DARWIN_ARM64_OPENSSL_ROOT}"
export TELEGRAM_PPC_PPC_ZLIB_ROOT="${TELEGRAM_PPC_PPC_ZLIB_ROOT:-$DARWIN_PPC_ZLIB_ROOT}"
export TELEGRAM_PPC_I386_ZLIB_ROOT="${TELEGRAM_PPC_I386_ZLIB_ROOT:-$DARWIN_I386_ZLIB_ROOT}"
export TELEGRAM_PPC_X86_64_ZLIB_ROOT="${TELEGRAM_PPC_X86_64_ZLIB_ROOT:-$DARWIN_X86_64_ZLIB_ROOT}"
export TELEGRAM_PPC_ARM64_ZLIB_ROOT="${TELEGRAM_PPC_ARM64_ZLIB_ROOT:-$DARWIN_ARM64_ZLIB_ROOT}"

export TELEGRAM_PPC_PPC_TDLIB_LIBRARY="${TELEGRAM_PPC_PPC_TDLIB_LIBRARY:-$DARWIN_PPC_TDLIB_LIBRARY}"
export TELEGRAM_PPC_I386_TDLIB_LIBRARY="${TELEGRAM_PPC_I386_TDLIB_LIBRARY:-$DARWIN_I386_TDLIB_LIBRARY}"
export TELEGRAM_PPC_X86_64_TDLIB_LIBRARY="${TELEGRAM_PPC_X86_64_TDLIB_LIBRARY:-$DARWIN_X86_64_TDLIB_LIBRARY}"
export TELEGRAM_PPC_ARM64_TDLIB_LIBRARY="${TELEGRAM_PPC_ARM64_TDLIB_LIBRARY:-$DARWIN_ARM64_TDLIB_LIBRARY}"

export TELEGRAM_PPC_PPC_BUNDLE_LIBS="${TELEGRAM_PPC_PPC_BUNDLE_LIBS:-${DARWIN_PPC_BUNDLE_LIBS:-}}"
export TELEGRAM_PPC_I386_BUNDLE_LIBS="${TELEGRAM_PPC_I386_BUNDLE_LIBS:-${DARWIN_I386_BUNDLE_LIBS:-}}"
export TELEGRAM_PPC_X86_64_BUNDLE_LIBS="${TELEGRAM_PPC_X86_64_BUNDLE_LIBS:-${DARWIN_X86_64_BUNDLE_LIBS:-}}"
export TELEGRAM_PPC_ARM64_BUNDLE_LIBS="${TELEGRAM_PPC_ARM64_BUNDLE_LIBS:-${DARWIN_ARM64_BUNDLE_LIBS:-}}"

export TELEGRAM_PPC_PPC_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_PPC_FFMPEG_EXTRA_LIBS:-${DARWIN_PPC_FFMPEG_EXTRA_LIBS:-}}"
export TELEGRAM_PPC_I386_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_I386_FFMPEG_EXTRA_LIBS:-${DARWIN_I386_FFMPEG_EXTRA_LIBS:-}}"
export TELEGRAM_PPC_X86_64_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_X86_64_FFMPEG_EXTRA_LIBS:-${DARWIN_X86_64_FFMPEG_EXTRA_LIBS:-}}"
export TELEGRAM_PPC_ARM64_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_ARM64_FFMPEG_EXTRA_LIBS:-${DARWIN_ARM64_FFMPEG_EXTRA_LIBS:-}}"
export TELEGRAM_PPC_FFMPEG_LINKAGE="${TELEGRAM_PPC_FFMPEG_LINKAGE:-${DARWIN_FFMPEG_LINKAGE:-static}}"
