#!/usr/bin/env bash

# Copy this file to local-build-config.sh and fill in paths for your machine.
# The real config is intentionally ignored by git.

export TELEGRAM_PPC_BUILD_ROOT="${TELEGRAM_PPC_BUILD_ROOT:-$PWD/../telegramppc-build}"
export TELEGRAM_PPC_DIST_DIR="${TELEGRAM_PPC_DIST_DIR:-$PWD/dist}"
export TELEGRAM_PPC_DEPENDENCY_ROOTS="${TELEGRAM_PPC_DEPENDENCY_ROOTS:-}"
export TELEGRAM_PPC_SDK_ROOT="${TELEGRAM_PPC_SDK_ROOT:-/path/to/MacOSX10.5.sdk}"
export TELEGRAM_PPC_ARM64_SDK_ROOT="${TELEGRAM_PPC_ARM64_SDK_ROOT:-/path/to/modern/MacOSX.sdk}"
export TELEGRAM_PPC_INSTALL_NAME_TOOL="${TELEGRAM_PPC_INSTALL_NAME_TOOL:-/path/to/install_name_tool}"
export TELEGRAM_PPC_OTOOL="${TELEGRAM_PPC_OTOOL:-/path/to/otool}"
export TELEGRAM_PPC_LIPO="${TELEGRAM_PPC_LIPO:-/path/to/lipo}"
export TELEGRAM_PPC_CA_BUNDLE="${TELEGRAM_PPC_CA_BUNDLE:-/path/to/cacert.pem}"
export TELEGRAM_PPC_JOBS="${TELEGRAM_PPC_JOBS:-2}"
export TELEGRAM_PPC_VERSION="${TELEGRAM_PPC_VERSION:-0.2.1}"
export TELEGRAM_PPC_BUILD_NUMBER="${TELEGRAM_PPC_BUILD_NUMBER:-0}"

# Release toolchains. Native single-architecture builds do not need this file.
export TELEGRAM_PPC_PPC_CXX="${TELEGRAM_PPC_PPC_CXX:-/path/to/powerpc-apple-darwin9-g++}"
export TELEGRAM_PPC_I386_CXX="${TELEGRAM_PPC_I386_CXX:-/path/to/i686-apple-darwin9-g++}"
export TELEGRAM_PPC_X86_64_CXX="${TELEGRAM_PPC_X86_64_CXX:-/path/to/x86_64-apple-darwin9-g++}"
export TELEGRAM_PPC_ARM64_CXX="${TELEGRAM_PPC_ARM64_CXX:-/path/to/arm64-apple-darwin-g++}"
export TELEGRAM_PPC_PPC_CC="${TELEGRAM_PPC_PPC_CC:-/path/to/powerpc-apple-darwin9-gcc}"
export TELEGRAM_PPC_I386_CC="${TELEGRAM_PPC_I386_CC:-/path/to/i686-apple-darwin9-gcc}"
export TELEGRAM_PPC_X86_64_CC="${TELEGRAM_PPC_X86_64_CC:-/path/to/x86_64-apple-darwin9-gcc}"
export TELEGRAM_PPC_ARM64_CC="${TELEGRAM_PPC_ARM64_CC:-/path/to/arm64-apple-darwin-gcc}"

# Per-architecture dependency prefixes.
export TELEGRAM_PPC_PPC_FFMPEG_ROOT="${TELEGRAM_PPC_PPC_FFMPEG_ROOT:-/path/to/ffmpeg-ppc}"
export TELEGRAM_PPC_I386_FFMPEG_ROOT="${TELEGRAM_PPC_I386_FFMPEG_ROOT:-/path/to/ffmpeg-i386}"
export TELEGRAM_PPC_X86_64_FFMPEG_ROOT="${TELEGRAM_PPC_X86_64_FFMPEG_ROOT:-/path/to/ffmpeg-x86_64}"
export TELEGRAM_PPC_ARM64_FFMPEG_ROOT="${TELEGRAM_PPC_ARM64_FFMPEG_ROOT:-/path/to/ffmpeg-arm64}"
export TELEGRAM_PPC_PPC_CURL_ROOT="${TELEGRAM_PPC_PPC_CURL_ROOT:-/path/to/curl-static-ppc}"
export TELEGRAM_PPC_I386_CURL_ROOT="${TELEGRAM_PPC_I386_CURL_ROOT:-/path/to/curl-static-i386}"
export TELEGRAM_PPC_X86_64_CURL_ROOT="${TELEGRAM_PPC_X86_64_CURL_ROOT:-/path/to/curl-static-x86_64}"
export TELEGRAM_PPC_ARM64_CURL_ROOT="${TELEGRAM_PPC_ARM64_CURL_ROOT:-/path/to/curl-static-arm64}"
export TELEGRAM_PPC_PPC_OPENSSL_ROOT="${TELEGRAM_PPC_PPC_OPENSSL_ROOT:-/path/to/openssl-ppc}"
export TELEGRAM_PPC_I386_OPENSSL_ROOT="${TELEGRAM_PPC_I386_OPENSSL_ROOT:-/path/to/openssl-i386}"
export TELEGRAM_PPC_X86_64_OPENSSL_ROOT="${TELEGRAM_PPC_X86_64_OPENSSL_ROOT:-/path/to/openssl-x86_64}"
export TELEGRAM_PPC_ARM64_OPENSSL_ROOT="${TELEGRAM_PPC_ARM64_OPENSSL_ROOT:-/path/to/openssl-arm64}"
export TELEGRAM_PPC_PPC_ZLIB_ROOT="${TELEGRAM_PPC_PPC_ZLIB_ROOT:-/path/to/zlib-ppc}"
export TELEGRAM_PPC_I386_ZLIB_ROOT="${TELEGRAM_PPC_I386_ZLIB_ROOT:-/path/to/zlib-i386}"
export TELEGRAM_PPC_X86_64_ZLIB_ROOT="${TELEGRAM_PPC_X86_64_ZLIB_ROOT:-/path/to/zlib-x86_64}"
export TELEGRAM_PPC_ARM64_ZLIB_ROOT="${TELEGRAM_PPC_ARM64_ZLIB_ROOT:-/path/to/zlib-arm64}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_ROOT="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_ROOT:-/path/to/ffmpeg-static-ppc}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_ROOT="${TELEGRAM_PPC_I386_STATIC_FFMPEG_ROOT:-/path/to/ffmpeg-static-i386}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_ROOT="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_ROOT:-/path/to/ffmpeg-static-x86_64}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_ROOT="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_ROOT:-/path/to/ffmpeg-static-arm64}"

export TELEGRAM_PPC_PPC_TDLIB_LIBRARY="${TELEGRAM_PPC_PPC_TDLIB_LIBRARY:-/path/to/ppc/libtdjson.1.8.65.dylib}"
export TELEGRAM_PPC_I386_TDLIB_LIBRARY="${TELEGRAM_PPC_I386_TDLIB_LIBRARY:-/path/to/i386/libtdjson.1.8.65.dylib}"
export TELEGRAM_PPC_X86_64_TDLIB_LIBRARY="${TELEGRAM_PPC_X86_64_TDLIB_LIBRARY:-/path/to/x86_64/libtdjson.1.8.65.dylib}"
export TELEGRAM_PPC_ARM64_TDLIB_LIBRARY="${TELEGRAM_PPC_ARM64_TDLIB_LIBRARY:-/path/to/arm64/libtdjson.1.8.65.dylib}"

# Optional dynamic dependencies that must be copied into the app.
export TELEGRAM_PPC_PPC_BUNDLE_LIBS="${TELEGRAM_PPC_PPC_BUNDLE_LIBS:-}"
export TELEGRAM_PPC_I386_BUNDLE_LIBS="${TELEGRAM_PPC_I386_BUNDLE_LIBS:-}"
export TELEGRAM_PPC_X86_64_BUNDLE_LIBS="${TELEGRAM_PPC_X86_64_BUNDLE_LIBS:-}"
export TELEGRAM_PPC_ARM64_BUNDLE_LIBS="${TELEGRAM_PPC_ARM64_BUNDLE_LIBS:-}"

# Set to static once the matching static FFmpeg builds exist.
export TELEGRAM_PPC_FFMPEG_LINKAGE="${TELEGRAM_PPC_FFMPEG_LINKAGE:-shared}"
export TELEGRAM_PPC_PPC_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_PPC_FFMPEG_EXTRA_LIBS:-}"
export TELEGRAM_PPC_I386_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_I386_FFMPEG_EXTRA_LIBS:-}"
export TELEGRAM_PPC_X86_64_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_X86_64_FFMPEG_EXTRA_LIBS:-}"
export TELEGRAM_PPC_ARM64_FFMPEG_EXTRA_LIBS="${TELEGRAM_PPC_ARM64_FFMPEG_EXTRA_LIBS:-}"

# Optional CMake arguments appended to each thin slice configure.
export TELEGRAM_PPC_CMAKE_ARGS="${TELEGRAM_PPC_CMAKE_ARGS:-}"

# Release verification rejects these load-command path patterns after bundling.
export TELEGRAM_PPC_FORBIDDEN_LOAD_PATH_PATTERN="${TELEGRAM_PPC_FORBIDDEN_LOAD_PATH_PATTERN:-/opt/local|/home/|/mnt/|/tmp/}"

export TELEGRAM_PPC_FFMPEG_SOURCE="${TELEGRAM_PPC_FFMPEG_SOURCE:-/path/to/ffmpeg/source}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_I386_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_EXTRA_CFLAGS="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_EXTRA_CFLAGS:-}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_EXTRA_LDFLAGS="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_EXTRA_LDFLAGS:-}"

# Optional. Set these only if the compiler prefix does not provide plain ar/ranlib/strip tools.
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_AR="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_AR:-}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_RANLIB="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_RANLIB:-}"
export TELEGRAM_PPC_PPC_STATIC_FFMPEG_STRIP="${TELEGRAM_PPC_PPC_STATIC_FFMPEG_STRIP:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_AR="${TELEGRAM_PPC_I386_STATIC_FFMPEG_AR:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_RANLIB="${TELEGRAM_PPC_I386_STATIC_FFMPEG_RANLIB:-}"
export TELEGRAM_PPC_I386_STATIC_FFMPEG_STRIP="${TELEGRAM_PPC_I386_STATIC_FFMPEG_STRIP:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_AR="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_AR:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_RANLIB="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_RANLIB:-}"
export TELEGRAM_PPC_X86_64_STATIC_FFMPEG_STRIP="${TELEGRAM_PPC_X86_64_STATIC_FFMPEG_STRIP:-}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_AR="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_AR:-}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_RANLIB="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_RANLIB:-}"
export TELEGRAM_PPC_ARM64_STATIC_FFMPEG_STRIP="${TELEGRAM_PPC_ARM64_STATIC_FFMPEG_STRIP:-}"
